[[redirects]]
  from = "/en"
  to = "/en/home/"
  status = 301
  force = true

[[redirects]]
  from = "/fr/"
  to = "/fr/"
  status = 301
  force = true

[[redirects]]
  from = "/fr/home/"
  to = "/fr/"
  status = 301
  force = true